name: Called Example
run-name: Called ${{ inputs.sites }}

on:
  workflow_call:
    inputs:
      sites:
        required: true
        type: string

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Reusing workflows
        run: |
          make echo_hello_world
